---
 - name: Create several Users
   hosts: all
   vars_files: user_list.yml
  
   tasks:
   - name: Add 5 users
     become: yes
     with_dict: "{{ users }}"
     user:
       name: "{{ item.key }}"
       password: "{{ item.value | password_hash ('sha512')}}"
       state: present
       update_password: on_create
     no_log: true